name: Build Nvidia akmods cache

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

env:
  IMAGE_REGISTRY: ghcr.io/${{ github.repository_owner }}

jobs:
  build:
    name: Build Nvidia akmods cache
    runs-on: ubuntu-latest
    strategy:
      matrix:
        fedora-version: [37, 38]
        nvidia-version: [530]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate Tags
        shell: bash
        run: |
          version_tag="${{ matrix.fedora-version }}-${{ matrix.nvidia-version }}"
          sha_tag="${GITHUB_SHA::8}-${{ matrix.fedora-version }}-${{ matrix.nvidia-version }}"

          tags=(
            ${version_tag}
            ${sha_tag}
          )

          echo "TAGS=${tags[*]}" >> $GITHUB_ENV
          echo "SHA_TAG=${sha_tag}" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: nvidia/Containerfile
          push: true
          tags: ${{ env.TAGS}}
          cache-from: type=gha
          cache-to: type=gha,mode=max
