name: Build Nvidia akmods cache

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0,12 * * *'
  pull_request:
  workflow_dispatch:

env:
  IMAGE_REGISTRY: ghcr.io/${{ github.repository_owner }}
  IMAGE_NAME: akmods-nvidia

jobs:
  build:
    name: Build Nvidia akmods cache
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        fedora-version: [38, 39, 40]
        nvidia-version: [550]

    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

      - name: Generate Image Metadata
        id: generate-meta
        shell: bash
        run: |
          tags=()
          tags+=("${{ env.IMAGE_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ matrix.fedora-version }}-${{ matrix.nvidia-version }}")
          tags+=("${{ env.IMAGE_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ matrix.fedora-version }}-${{ matrix.nvidia-version }}-$(date +%Y%m%d%H%M%S)")
          tags+=("${{ env.IMAGE_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ matrix.fedora-version }}-${{ matrix.nvidia-version }}-${GITHUB_SHA::7}")

          echo "tags=${tags[*]}" >> $GITHUB_OUTPUT
          concat_tags=$(IFS=, ; echo "${tags[*]}")
          echo "concat_tags=$concat_tags" >> $GITHUB_OUTPUT

      - name: Fetch akmods signing key
        run: |
          echo "${{ secrets.AKMODS_PRIVATE_KEY }}" > _certs/private_key.priv

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@0d103c3126aa41d772a8362f6aa67afac040f80c # v3

      - name: Login to GHCR
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Image
        id: build-image
        uses: docker/build-push-action@af5a7ed5ba88268d5278f7203fb52cd833f66d6e # v5
        with:
          file: nvidia/Containerfile
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.generate-meta.outputs.concat_tags }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            NVIDIA_VERSION=${{ matrix.nvidia-version }}
            FEDORA_VERSION=${{ matrix.fedora-version }}
            RPMFUSION_TESTING_ENABLED=${{ matrix.rpmfusion-testing-enabled }}

  check:
    needs: [build]
    if: ${{ !cancelled() }}
    runs-on: ubuntu-latest
    steps:
      - name: Exit on failure
        if: ${{ needs.build.result == 'failure' }}
        shell: bash
        run: exit 1

      - name: Exit on success
        shell: bash
        run: exit 0
