name: Build Nvidia akmods cache

on:
  pull_request:
    branches:
      - main

env:
  IMAGE_REGISTRY: ghcr.io/${{ github.repository_owner }}
  IMAGE_NAME: akmods-nvidia

jobs:
  build:
    name: Build Nvidia akmods cache
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        fedora-version: [37, 38]
        nvidia-version: [530]

    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate Image Metadata
        id: generate-meta
        shell: bash
        run: |
          tags=()
          tags+=("${{ env.IMAGE_REGISTRY }}/${{ matrix.fedora-version }}-${{ matrix.nvidia-version }}")
          tags+=("${{ env.IMAGE_REGISTRY }}/${{ matrix.fedora-version }}-${{ matrix.nvidia-version }}-$(date +%Y%m%d%H%M%S)")
          tags+=("${{ env.IMAGE_REGISTRY }}/${{ matrix.fedora-version }}-${{ matrix.nvidia-version }}-${GITHUB_SHA::7}")

          echo "tags=${tags[*]}" >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Image
        id: build-image
        uses: docker/build-push-action@v4
        with:
          file: nvidia/Containerfile
          push: true
          tags: ${{ steps.generate-meta.outputs.tags }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
