name: Clear cache

on:
  workflow_dispatch:

permissions:
  actions: write

jobs:
  clear-cache:
    runs-on: ubuntu-latest
    steps:
      - name: Clear cache
        uses: actions/github-script@d7906e4ad0b1822421a7e6a35d5ca353c962f410 # v6
        with:
          script: |
            console.log("About to clear")
            let page = 1;
            let allCaches = [];

            while (true) {
              const caches = await github.rest.actions.getActionsCacheList({
                owner: context.repo.owner,
                repo: context.repo.repo,
                page: page,
                per_page: 100,
              });

              if (caches.data.actions_caches.length === 0) {
                break;
              }

              allCaches = allCaches.concat(caches.data.actions_caches);
              page++;
            }

            for (const cache of allCaches) {
              console.log(cache);
              github.rest.actions.deleteActionsCacheById({
                owner: context.repo.owner,
                repo: context.repo.repo,
                cache_id: cache.id,
              });
            }

            console.log("Clear completed");
